"""Canonical economics contracts and legacy domain helpers."""

from .kernel import (
    CurrencyMismatchError,
    EconomicsError,
    EvidenceRef,
    MarketLane,
    Money,
    ServiceEconomics,
    CanonicalUnitEconomics,
    UnitEconomicsAssumptions,
    UnitEconomicsInputs,
    UnitEconomicsResult,
    calculate_scenarios,
    calculate_service_economics,
    calculate_unit_economics,
    canonical_json,
    incremental_contribution,
    orders_required_to_recover_fee,
    sensitivity_matrix,
    sensitivity,
    calculate_unit_economics_scenarios,
)

__all__ = [
    "CurrencyMismatchError",
    "EconomicsError",
    "EvidenceRef",
    "MarketLane",
    "Money",
    "ServiceEconomics",
    "CanonicalUnitEconomics",
    "UnitEconomicsAssumptions",
    "UnitEconomicsInputs",
    "UnitEconomicsResult",
    "calculate_scenarios",
    "calculate_service_economics",
    "calculate_unit_economics",
    "canonical_json",
    "incremental_contribution",
    "orders_required_to_recover_fee",
    "sensitivity_matrix",
    "sensitivity",
    "calculate_unit_economics_scenarios",
]
