from __future__ import annotations


def get_cockpit_action_catalog():
    common = {"requires_approval": True, "mutates_local_state": True, "external_effects": False, "forbidden_payload_keys": ["live", "mutate", "publish", "send", "order", "pay", "spend", "launch", "shell", "python", "url"]}
    return {
        "run_workflow": {**common, "endpoint": "/api/workflows/run", "callable": "backend.workflows.orchestrator.run_workflow", "allowed_payload_keys": ["workspace_id", "workflow_type", "title", "objective", "payload", "stop_after_stage"], "produces": ["workflow_id"]},
        "resume_workflow": {**common, "endpoint": "/api/workflows/{workflow_id}/resume", "callable": "backend.workflows.orchestrator.resume_workflow", "allowed_payload_keys": ["workflow_id", "from_stage", "checkpoint_id"], "produces": ["workflow_id"]},
        "replay_workflow_stage": {**common, "endpoint": "/api/workflows/{workflow_id}/replay-stage", "callable": "backend.workflows.orchestrator.replay_workflow_stage", "allowed_payload_keys": ["workflow_id", "stage_name", "reason"], "produces": ["workflow_id"]},
        "generate_optimization": {**common, "endpoint": "/api/optimization/portfolio", "callable": "backend.optimization.optimizer.build_portfolio_optimization_plan", "allowed_payload_keys": ["workspace_id", "objective", "constraints"], "produces": ["optimization_id", "action_set_id"]},
        "create_operating_plan": {**common, "endpoint": "/api/operations/plans", "callable": "backend.operations.operations_runner.create_operating_plan_cycle", "allowed_payload_keys": ["workspace_id", "optimization_id", "horizon", "max_tasks", "daily_hour_capacity", "create_calendar", "create_packets", "create_review_cadence"], "produces": ["plan_id", "task_id", "calendar_id"]},
        "update_task_status": {**common, "endpoint": "/api/operations/tasks/{task_id}/status", "callable": "backend.operations.operations_runner.update_task_status", "allowed_payload_keys": ["task_id", "status", "note", "produced_outputs"], "produces": ["task_id"]},
        "create_progress_review": {**common, "endpoint": "/api/operations/progress-review", "callable": "backend.operations.operations_runner.create_progress_review", "allowed_payload_keys": ["plan_id", "completed_task_ids", "blocked_task_ids", "cancelled_task_ids", "produced_outputs"], "produces": ["progress_snapshot_id"]},
        "run_executive_intelligence": {**common, "endpoint": "/api/intelligence/cycle", "callable": "backend.intelligence.executive_command_runner.run_executive_intelligence_cycle", "allowed_payload_keys": ["workspace_id", "objective", "build_graph", "build_priorities", "build_campaigns", "build_brief"], "produces": ["brief_id"]},
        "generate_deliverable": {**common, "endpoint": "/api/deliverables/product-validation-sprint", "callable": "backend.deliverables.product_validation_sprint.build_product_validation_sprint_package", "allowed_payload_keys": ["workspace_id", "sprint_id", "snapshot_id", "title", "objective", "include_appendices"], "produces": ["package_id"]},
        "run_validation_sprint": {**common, "endpoint": "/api/discovery/validation-sprints", "callable": "backend.discovery.validation_sprint_runner.run_validation_sprint", "allowed_payload_keys": ["workspace_id", "opportunity_ids", "title", "objective", "limit", "apply_transitions"], "produces": ["sprint_id"]},
        "refresh_pipeline": {**common, "endpoint": "/api/discovery/opportunity-pipeline/refresh", "callable": "backend.discovery.opportunity_pipeline_builder.refresh_opportunity_pipeline", "allowed_payload_keys": ["workspace_id", "discovery_id", "hypothesis_run_id"], "produces": ["snapshot_id"]},
        "run_refinement": {**common, "endpoint": "/api/discovery/refinement-cycle", "callable": "backend.discovery.refinement_runner.run_refinement_cycle", "allowed_payload_keys": ["workspace_id", "discovery_id", "hypothesis_run_id", "create_templates", "max_recommendations", "refresh_pipeline"], "produces": ["analysis_id", "plan_id"]},
        "run_source_calibration": {**common, "endpoint": "/api/discovery/source-calibration", "callable": "backend.discovery.source_calibration_engine.run_source_calibration", "allowed_payload_keys": ["workspace_id", "comparison_ids", "import_ids"], "produces": ["calibration_id"]},
        "advisory_manual": {"requires_approval": False, "mutates_local_state": False, "external_effects": False, "endpoint": "", "callable": None, "allowed_payload_keys": [], "produces": [], "forbidden_payload_keys": []},
        "blocked": {"requires_approval": False, "mutates_local_state": False, "external_effects": False, "endpoint": "", "callable": None, "allowed_payload_keys": [], "produces": [], "forbidden_payload_keys": []},
    }
