import type {
  DataMode,
  OwnerCandidate,
  OwnerDashboardViewModel,
  OwnerLoadState,
  OwnerNotice,
  OwnerRun,
  ReadinessSummary,
} from "../contracts/ownerDashboard.ts";
import { formatFreshnessLabel, isStaleFreshness } from "../../first-phase-cockpit/lib/freshness.ts";
import { adaptDiscoveryRun, type AdaptErrorCode } from "./adaptDiscoveryRun.ts";
import { composePerformance } from "./performance.ts";

export interface ComposeInput {
  load: OwnerLoadState;
  dataMode: DataMode;
  nowMs: number;
  /** True when a refresh failed but earlier data is still being shown. */
  refreshFailed?: boolean;
}

export const SAVE_TO_PORTFOLIO_DISABLED = {
  enabled: false as const,
  reason: "Not connected: no authorized portfolio backend exists yet, so nothing can be saved from this page.",
};

const ADAPT_ERROR_MESSAGES: Record<AdaptErrorCode, string> = {
  not_an_object: "The response was not a discovery run object.",
  unsupported_run_version: "The response uses a discovery run version this dashboard does not support.",
  decisions_missing: "The response did not include a decisions list.",
};

const TONE_ORDER = { danger: 0, warning: 1, info: 2 } as const;
const STALE_AFTER_HOURS = 24;

function empty(dataMode: DataMode, notices: OwnerNotice[]): OwnerDashboardViewModel {
  return {
    status: "loading",
    dataMode,
    notices,
    error: null,
    run: null,
    summary: null,
    ranked: [],
    unranked: [],
    performance: composePerformance(null),
    saveToPortfolio: SAVE_TO_PORTFOLIO_DISABLED,
  };
}

function demoNotice(dataMode: DataMode): OwnerNotice[] {
  return dataMode === "fixture_demo"
    ? [
        {
          id: "demo_data",
          tone: "info",
          title: "Demo data",
          detail:
            "These opportunities come from a fixture generated by MarketOS's offline discovery service. They are not your portfolio, not live market data, and not connected to Shopify or any account.",
        },
      ]
    : [];
}

function summarize(candidates: OwnerCandidate[]): ReadinessSummary {
  return {
    total: candidates.length,
    rankedCount: candidates.filter((c) => c.rank !== null).length,
    researchReadyCount: candidates.filter((c) => c.readiness === "ready").length,
    needsEvidenceCount: candidates.filter((c) => c.readiness === "not_ready").length,
    blockedCount: candidates.filter((c) => c.readiness === "blocked").length,
    readyUnscoredCount: candidates.filter((c) => c.unrankedReason === "ready_unscored").length,
    launchAuthorized: false,
  };
}

function plural(count: number, one: string, many: string): string {
  return `${count} ${count === 1 ? one : many}`;
}

function buildNotices(run: OwnerRun, input: ComposeInput, asOf: string | null): OwnerNotice[] {
  const notices: OwnerNotice[] = [...demoNotice(input.dataMode)];

  const integrity: string[] = [];
  if (!run.safetyPresent) integrity.push("the provider sent no safety flags");
  if (run.safetyViolations.length > 0) {
    integrity.push(`safety flags outside the read-only contract: ${run.safetyViolations.join(", ")}`);
  }
  const externalClaims = run.candidates.filter((c) => c.providerClaimedExternalAction).map((c) => c.candidateId);
  if (externalClaims.length > 0) integrity.push(`external action claimed allowed for ${externalClaims.join(", ")}`);
  if (integrity.length > 0) {
    notices.push({
      id: "provider_integrity",
      tone: "danger",
      title: "Provider response deviates from the read-only contract",
      detail: `${integrity.join("; ")}. This dashboard is advisory and cannot authorize launches or actions; those claims are ignored. Treat this run with caution.`,
    });
  }

  if (asOf === null) {
    if (input.dataMode !== "fixture_demo") {
      notices.push({
        id: "freshness_unknown",
        tone: "warning",
        title: "Freshness unknown",
        detail: "This data carries no timestamp, so its age cannot be judged.",
      });
    }
  } else {
    const label = formatFreshnessLabel(asOf, input.nowMs);
    if (label === "freshness_unavailable") {
      notices.push({
        id: "freshness_unknown",
        tone: "warning",
        title: "Freshness unknown",
        detail: "The data timestamp could not be read, so its age cannot be judged.",
      });
    } else if (isStaleFreshness(label, STALE_AFTER_HOURS)) {
      notices.push({
        id: "stale",
        tone: "warning",
        title: "Data may be stale",
        detail: `This data is older than ${STALE_AFTER_HOURS} hours (${label}). Recheck before relying on it.`,
      });
    }
  }
  if (input.refreshFailed) {
    notices.push({
      id: "stale",
      tone: "warning",
      title: "Showing the last loaded data",
      detail: "The latest refresh failed, so what you see may be out of date. Try again to refresh.",
    });
  }

  const aging = run.candidates.reduce(
    (total, c) => total + c.evidence.filter((e) => e.freshness === "stale" || e.freshness === "future" || e.freshness === "unknown").length,
    0,
  );
  if (aging > 0) {
    notices.push({
      id: "evidence_freshness",
      tone: "warning",
      title: "Some evidence is stale or of unknown age",
      detail: `${plural(aging, "evidence item is", "evidence items are")} stale, future-dated, or of unknown age.`,
    });
  }

  if (run.dropped.length > 0) {
    const sample = run.dropped.slice(0, 3).join("; ");
    notices.push({
      id: "partial_records",
      tone: "warning",
      title: "Some provider records were skipped",
      detail: `${plural(run.dropped.length, "record was", "records were")} unreadable and skipped (${sample}${run.dropped.length > 3 ? "; …" : ""}). What is shown is incomplete.`,
    });
  }

  return notices.sort((a, b) => TONE_ORDER[a.tone] - TONE_ORDER[b.tone]);
}

export function composeOwnerDashboard(input: ComposeInput): OwnerDashboardViewModel {
  const { load, dataMode } = input;

  if (load.status === "loading") return empty(dataMode, demoNotice(dataMode));

  if (load.status === "error") {
    return {
      ...empty(dataMode, demoNotice(dataMode)),
      status: "unavailable",
      error: {
        code: load.code ?? "source_unavailable",
        message: "The discovery data could not be loaded. Nothing below is shown as live data.",
      },
    };
  }

  const adapted = adaptDiscoveryRun(load.payload.run);
  if (!adapted.ok) {
    return {
      ...empty(dataMode, demoNotice(dataMode)),
      status: "malformed",
      error: { code: adapted.code, message: ADAPT_ERROR_MESSAGES[adapted.code] },
    };
  }

  const run = adapted.run;
  const ranked = run.candidates.filter((c) => c.rank !== null).sort((a, b) => (a.rank as number) - (b.rank as number));
  const unranked = run.candidates.filter((c) => c.rank === null);

  return {
    status: run.candidates.length === 0 ? "empty" : "ready",
    dataMode,
    notices: buildNotices(run, input, load.payload.asOf),
    error: null,
    run: {
      providerStatus: run.providerStatus,
      executionClassification: run.executionClassification,
      nextBestAction: run.nextBestAction,
      fingerprintShort: run.fingerprint ? run.fingerprint.slice(0, 12) : null,
      blockers: run.blockers,
    },
    summary: summarize(run.candidates),
    ranked,
    unranked,
    performance: composePerformance(load.payload.performance),
    saveToPortfolio: SAVE_TO_PORTFOLIO_DISABLED,
  };
}
