from __future__ import annotations

from typing import Any

from .import_recommendation import _FIELDS


_PLAYBOOKS: dict[str, dict[str, Any]] = {
    "google_trends_csv": {"title": "Google Trends local export", "description": "A manually prepared trend/keyword export for directional trend evidence.", "steps": ["Open the source manually and choose the category, terms, geography, and time window.", "Export or manually transcribe the result into the approved template.", "Record the export date and geography in provenance before import."], "signals": ["trend_proxy"], "invalid": ["Do not infer conversion, profitability, or ROAS from trend scores."], "checks": ["Confirm geography and timeframe are present.", "Confirm rows are not synthetic placeholders.", "Confirm source file and export date are documented."], "safety": ["Manual/cache-only; no credentials or network calls are used by MarketOS."], "future": "A future connector would require an audited read-only export contract and explicit cache boundary."},
    "tiktok_creative_center_csv": {"title": "TikTok Creative Center snapshot", "description": "A manually compiled creative/product/category observation export.", "steps": ["Review the relevant category and geography manually.", "Record observed creative/product fields in the template.", "Document the observation date and source context."], "signals": ["creative_proxy", "trend_proxy", "competition_proxy"], "invalid": ["Do not infer profitability or durable demand from views, likes, or ad counts."], "checks": ["Separate observations from estimates.", "Record region and observation date.", "Do not include credentials or account data."], "safety": ["MarketOS only ingests the local file."], "future": "Future automation must be read-only, rate-limited, provenance-preserving, and disabled by default."},
    "amazon_bestsellers_csv": {"title": "Amazon bestseller snapshot", "description": "A manually prepared category/product/rank/price/review snapshot.", "steps": ["Select a category and geography manually.", "Record rank, price, reviews, and rating in the template.", "Record the snapshot date and clarify that rank is only a proxy."], "signals": ["competition_proxy", "demand_proxy", "price_signal"], "invalid": ["Do not treat rank as exact sales or infer profit without supplier economics."], "checks": ["Rank and price must be numeric when supplied.", "Snapshot date and category must be present.", "Do not bypass access controls or rate limits."], "safety": ["Manual/local snapshot only; no scraping is performed."], "future": "Any future connector requires legal/source-policy review and an approved cached output."},
    "meta_ad_library_csv": {"title": "Meta Ad Library snapshot", "description": "A manually compiled advertiser/product/ad activity observation.", "steps": ["Review the public library manually for the selected category and region.", "Record advertiser, product, ad count, and active days.", "Document observation date and platform."], "signals": ["competition_proxy", "creative_proxy"], "invalid": ["Do not treat ad count as demand, sales, or profitability."], "checks": ["Platform, region, and observation date are documented.", "Only public observations are used.", "No account credentials or campaign controls are included."], "safety": ["No ad creation, editing, or platform write is possible."], "future": "Future acquisition must be read-only and explicitly audited."},
    "reddit_keyword_csv": {"title": "Reddit audience and pain-point export", "description": "A manually compiled keyword, community, and pain-point observation.", "steps": ["Select relevant public communities manually.", "Record terms, mentions, engagement, and pain-point language.", "Document the observation window and limitations."], "signals": ["audience_proxy", "pain_point", "trend_proxy"], "invalid": ["Do not infer market size or representativeness from community activity."], "checks": ["Remove usernames and personal data.", "Record community and time window.", "Mark sentiment as observational, not causal."], "safety": ["Local import only; no automated collection."], "future": "Any connector requires privacy, policy, and provenance review."},
    "mercadolibre_snapshot_csv": {"title": "MercadoLibre marketplace snapshot", "description": "A manually prepared marketplace price, seller, review, and optional sold-count snapshot.", "steps": ["Review the selected category and region manually.", "Record product, price, sellers, reviews, and sold_count only when explicitly shown.", "Document the snapshot date."], "signals": ["price_signal", "competition_proxy", "demand_proxy"], "invalid": ["Do not infer demand when sold_count is absent; do not infer profitability."], "checks": ["Currency and region are documented.", "sold_count is labeled as explicit or absent.", "No marketplace mutation is performed."], "safety": ["Manual/cache-only snapshot."], "future": "Future connectors require source-policy and read-only review."},
    "supplier_catalog_csv": {"title": "Supplier catalog and logistics export", "description": "A local supplier catalog for cost, shipping, MOQ, lead time, and availability assumptions.", "steps": ["Obtain an authorized catalog export manually.", "Record supplier and logistics fields in the template.", "Document currency, export date, and supplier identity."], "signals": ["margin_proxy", "supplier_proxy", "risk_proxy", "price_signal"], "invalid": ["Do not infer demand from supplier availability; do not treat quoted cost as guaranteed."], "checks": ["Currency and shipping basis are documented.", "MOQ and lead time are numeric where present.", "Supplier data is authorized and contains no secrets."], "safety": ["No supplier ordering or account mutation is possible."], "future": "Future connector requires explicit supplier authorization and dry-run contract."},
    "shopify_orders_csv": {"title": "Own Shopify orders export", "description": "A manually exported first-party order history for the user’s own store.", "steps": ["Export only the required order/product fields from the user’s own store.", "Remove customer names, addresses, emails, and payment details.", "Record the period and currency before import."], "signals": ["own_store_sales_proxy", "price_signal", "risk_proxy"], "invalid": ["Do not treat own-store sales as general market demand or expose customer data."], "checks": ["Confirm the export belongs to the workspace owner.", "Remove personal data and secrets.", "Document refunds and period."], "safety": ["MarketOS does not connect to or mutate Shopify in this phase."], "future": "Future connector requires credential isolation, privacy review, and read-only scopes."},
    "stripe_payments_csv": {"title": "Own Stripe payments export", "description": "A manually exported first-party payment history for the user’s own business.", "steps": ["Export only product, amount, currency, status, and refund fields.", "Remove customer identifiers and payment instrument data.", "Record period and export provenance."], "signals": ["own_store_sales_proxy", "price_signal", "risk_proxy"], "invalid": ["Do not treat payment history as general market demand or expose payment data."], "checks": ["Confirm first-party ownership.", "Remove PII and payment details.", "Confirm currency and refund semantics."], "safety": ["No payment execution or account access is performed."], "future": "Future connector requires read-only scopes and security review."},
    "generic_market_csv": {"title": "Generic market evidence import", "description": "A fallback schema for documented local evidence when no specific parser applies.", "steps": ["Use a source-specific parser whenever possible.", "Provide entity, signal, value, confidence, and provenance fields.", "Document the evidence method and limitations."], "signals": ["trend_proxy", "demand_proxy", "competition_proxy", "margin_proxy", "audience_proxy", "creative_proxy", "price_signal", "supplier_proxy", "risk_proxy"], "invalid": ["Do not omit provenance or claim unsupported signals."], "checks": ["Signal type is from the allowed registry.", "Provenance identifies source and row.", "Confidence and weight are bounded."], "safety": ["Local file only; no external calls."], "future": "Generic connectors remain disabled until a source-specific audit exists."},
}


def get_source_playbook(parser_type: str) -> dict[str, Any]:
    if parser_type not in _PLAYBOOKS: raise ValueError("unsupported_parser_type")
    item = dict(_PLAYBOOKS[parser_type]); required, optional = _FIELDS[parser_type]
    item.update({"parser_type": parser_type, "required_fields": list(required), "optional_fields": list(optional), "expected_signal_types": list(item["signals"]), "manual_export_steps": list(item["steps"]), "invalid_claims": list(item["invalid"]), "verification_checks": list(item["checks"]), "safety_notes": list(item["safety"]), "template_hint": f"data/import_templates/{parser_type}.csv"})
    return item
