"""Regenerate ownerDemoDiscoveryRun.ts from the real offline discovery service.

Run from the repository root:
    python frontend/src/features/owner-dashboard/fixtures/generate_owner_demo_run.py

The payload is assembled from tests/fixtures/opportunity_discovery/*.json with
small, labelled edits (fictional "(demo)" products, filled economics inputs).
It is executed in-process by services.opportunity_discovery.run_discovery in
"compare" mode: no network, no credentials, no HTTP route involved.

Only subtrees the dashboard never reads are pruned (evidence_ref(s), exchange-rate
and uncertainty metadata, trustos_export, governor, review_results, and the input
echo on candidates) to keep the file reviewable. Everything the adapter reads is
verbatim provider output.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

from services.opportunity_discovery import run_discovery

ROOT = Path(__file__).resolve().parents[5]
OUT = Path(__file__).with_name("ownerDemoDiscoveryRun.ts")


def load(name: str) -> dict:
    return json.loads((ROOT / "tests/fixtures/opportunity_discovery" / f"{name}.json").read_text(encoding="utf-8"))


def money(amount: str) -> dict:
    return {"amount": amount, "currency": "MXN", "source": "demo", "provenance": "assumed", "evidence_state": "assumed"}


FILL = {
    "affiliate_fee_rate": "0.00",
    "brokerage_fee": money("0"),
    "cac": money("120"),
    "domestic_shipping": money("40"),
    "international_shipping": money("60"),
    "payment_fee_fixed": money("3"),
    "platform_fee_fixed": money("0"),
}


def rename(candidate: dict, cid: str, name: str, query: str) -> dict:
    c = copy.deepcopy(candidate)
    c["candidate_id"], c["name"] = cid, name
    for ev in c["evidence"]:
        ev["evidence_id"] = ev["evidence_id"].replace("desk", cid.split("-")[0])
        ev["source_ref"] = ev["source_ref"].replace("desk-lamp", cid)
    for report in c["reports"].values():
        for row in report.get("candidates", []):
            row["candidate_id"], row["query"] = cid, query
    return c


def build_payload() -> dict:
    lamp = load("product_complete")["candidates"][0]
    adversarial = {c["candidate_id"]: c for c in load("adversarial_cases")["candidates"]}

    # Complete economics inputs and strong scores -> research-ready and ranked.
    ranked = rename(lamp, "desk-lamp-pro", "Adjustable desk lamp (demo)", "adjustable desk lamp")
    ranked["economics"]["assumptions"].update(copy.deepcopy(FILL))
    marketplace = ranked["reports"]["marketplace"]["candidates"][0]["score"]
    supplier = ranked["reports"]["supplier"]["candidates"][0]["score"]
    consumer = ranked["reports"]["consumer"]["candidates"][0]["score"]
    marketplace["overall_marketplace_opportunity"] = 0.86
    supplier["overall_supplier_feasibility"] = 0.82
    consumer["overall_consumer_attention"] = 0.80

    # Original economics inputs left incomplete -> needs evidence (scored, but not ranked).
    needs_evidence = rename(lamp, "monitor-riser", "Monitor riser (demo)", "monitor riser")

    return {
        "run_id": "owner-dashboard-demo-v1",
        "candidates": [
            ranked,
            needs_evidence,
            copy.deepcopy(adversarial["restricted-category"]),
            copy.deepcopy(adversarial["supplier-claim-only"]),
        ],
    }


DROP_ANYWHERE = {"evidence_ref", "evidence_refs", "exchange_rate", "exchange_rate_timestamp", "uncertainty", "tax_inclusion_state"}
DROP_DECISION = {"trustos_export", "governor", "review_results"}
DROP_CANDIDATE = {"reports", "economics", "geography", "metadata"}


def prune(value):
    if isinstance(value, dict):
        return {k: prune(v) for k, v in value.items() if k not in DROP_ANYWHERE}
    if isinstance(value, list):
        return [prune(v) for v in value]
    return value


def main() -> None:
    run = run_discovery("compare", build_payload()).to_dict()
    pruned = prune(run)
    for decision in pruned["decisions"]:
        for key in DROP_DECISION:
            decision.pop(key, None)
    for candidate in pruned["candidates"]:
        for key in DROP_CANDIDATE:
            candidate.pop(key, None)
    header = (
        "// GENERATED by generate_owner_demo_run.py from the real offline discovery service\n"
        "// (services.opportunity_discovery.run_discovery, mode \"compare\", run in-process).\n"
        "// DEMO DATA: fictional products, not an API response, not live, not your portfolio.\n"
        "// Unread subtrees are pruned; see the generator for the exact list. Do not edit by hand.\n\n"
    )
    body = json.dumps(pruned, indent=1, ensure_ascii=False)
    OUT.write_text(f"{header}export const OWNER_DEMO_DISCOVERY_RUN: unknown = {body};\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes); ranked={run['ranked_candidate_ids']}")


if __name__ == "__main__":
    main()
