// GENERATED by generate_owner_demo_run.py from the real offline discovery service
// (services.opportunity_discovery.run_discovery, mode "compare", run in-process).
// DEMO DATA: fictional products, not an API response, not live, not your portfolio.
// Unread subtrees are pruned; see the generator for the exact list. Do not edit by hand.

export const OWNER_DEMO_DISCOVERY_RUN: unknown = {
 "run_version": "opportunity-discovery-v1",
 "mode": "compare",
 "status": "needs_evidence",
 "execution_classification": "actual_executed",
 "candidates": [
  {
   "candidate_id": "desk-lamp-pro",
   "name": "Adjustable desk lamp (demo)",
   "offering_kind": "product",
   "category": "home",
   "evidence": [
    {
     "evidence_id": "desk-demand",
     "area": "demand",
     "status": "observed_fact",
     "evidence_class": "fixture",
     "source_type": "fixture",
     "source_ref": "fixture://market/desk-lamp-pro",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    },
    {
     "evidence_id": "desk-economics",
     "area": "economics",
     "status": "assumption",
     "evidence_class": "derived",
     "source_type": "kernel",
     "source_ref": "derived://economics/desk-lamp-pro",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    },
    {
     "evidence_id": "desk-supply",
     "area": "supply",
     "status": "observed_fact",
     "evidence_class": "manual",
     "source_type": "operator",
     "source_ref": "manual://supplier/desk-lamp-pro",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    }
   ]
  },
  {
   "candidate_id": "monitor-riser",
   "name": "Monitor riser (demo)",
   "offering_kind": "product",
   "category": "home",
   "evidence": [
    {
     "evidence_id": "monitor-demand",
     "area": "demand",
     "status": "observed_fact",
     "evidence_class": "fixture",
     "source_type": "fixture",
     "source_ref": "fixture://market/monitor-riser",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    },
    {
     "evidence_id": "monitor-economics",
     "area": "economics",
     "status": "assumption",
     "evidence_class": "derived",
     "source_type": "kernel",
     "source_ref": "derived://economics/monitor-riser",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    },
    {
     "evidence_id": "monitor-supply",
     "area": "supply",
     "status": "observed_fact",
     "evidence_class": "manual",
     "source_type": "operator",
     "source_ref": "manual://supplier/monitor-riser",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    }
   ]
  },
  {
   "candidate_id": "restricted-category",
   "name": "Restricted",
   "offering_kind": "hybrid",
   "category": "restricted",
   "evidence": [
    {
     "evidence_id": "restricted",
     "area": "demand",
     "status": "hypothesis",
     "evidence_class": "fixture",
     "source_type": "fixture",
     "source_ref": "",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": []
    }
   ]
  },
  {
   "candidate_id": "supplier-claim-only",
   "name": "Claim only",
   "offering_kind": "product",
   "category": "home",
   "evidence": [
    {
     "evidence_id": "claim",
     "area": "supply",
     "status": "hypothesis",
     "evidence_class": "observed",
     "source_type": "supplier_claim",
     "source_ref": "manual://claim",
     "freshness": "current",
     "conflicting": false,
     "value": null,
     "notes": [
      "supplier_claim_is_not_independent_verification"
     ]
    }
   ]
  }
 ],
 "decisions": [
  {
   "candidate_id": "desk-lamp-pro",
   "recommendation": "attractive",
   "readiness": "ready",
   "fatal_gates": [],
   "blockers": [],
   "evidence_gaps": [],
   "evidence_classes": [
    "derived",
    "fixture",
    "manual"
   ],
   "metrics": {
    "synthesis_score": 0.831,
    "offering_kind": "product",
    "evidence_confidence": 0.6667,
    "economics_status": "derived",
    "economics_missing_inputs": []
   },
   "scenarios": {
    "best": {
     "scenario": "upside",
     "currency": "MXN",
     "net_sales": {
      "amount": "945.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "72.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "36.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "international_shipping": {
      "amount": "54.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "duty": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "151.200000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "demo",
      "provenance": "assumed",
      "evidence_state": "assumed"
     },
     "payment_fees": {
      "amount": "31.350000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "18.900000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "9.450000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0E-8",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "102.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "contribution_before_cac": {
      "amount": "266.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "164.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "266.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "77.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "780.90000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.2815873015873015873015873016",
     "contribution_margin_after_cac": "0.1736507936507936507936507937",
     "break_even_roas": "3.551296505073280721533258174",
     "target_roas": "12.25680933852140077821011673",
     "expected_return_cost": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": []
    },
    "base": {
     "scenario": "base",
     "currency": "MXN",
     "net_sales": {
      "amount": "900.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "80",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "40",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "international_shipping": {
      "amount": "60",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "duty": {
      "amount": "0.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "144.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "demo",
      "provenance": "assumed",
      "evidence_state": "assumed"
     },
     "payment_fees": {
      "amount": "30.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "9.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "120",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "contribution_before_cac": {
      "amount": "195.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "75.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "195.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "15.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "825.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.2166666666666666666666666667",
     "contribution_margin_after_cac": "0.08333333333333333333333333333",
     "break_even_roas": "4.615384615384615384615384615",
     "target_roas": "6E+1",
     "expected_return_cost": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": []
    },
    "worst": {
     "scenario": "downside",
     "currency": "MXN",
     "net_sales": {
      "amount": "810.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "96.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "48.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "international_shipping": {
      "amount": "72.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "duty": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "129.600000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "demo",
      "provenance": "assumed",
      "evidence_state": "assumed"
     },
     "payment_fees": {
      "amount": "27.300000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "16.200000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "8.100000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0E-8",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "150.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "assumed"
     },
     "contribution_before_cac": {
      "amount": "50.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "-99.90000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "50.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "0",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "909.90000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.06185185185185185185185185185",
     "contribution_margin_after_cac": "-0.1233333333333333333333333333",
     "break_even_roas": "16.16766467065868263473053892",
     "target_roas": "unknown",
     "expected_return_cost": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": []
    }
   },
   "sensitivity_drivers": [
    "evidence freshness"
   ],
   "experiment": {
    "experiment_id": "experiment-desk-lamp-pro",
    "question": "Which missing evidence would change the offline decision?",
    "method": "offline_sanitized_evidence_review",
    "required_evidence": [
     "independent evidence"
    ],
    "success_thresholds": {
     "required_evidence_count": 1,
     "decision_change": "all fatal gates clear"
    },
    "kill_thresholds": {
     "decision_change": "retain_block_or_reject"
    },
    "iterate_rule": "iterate only when new bounded evidence changes a named blocker; otherwise stop",
    "estimated_cost": {
     "currency": "unknown",
     "amount": "unknown",
     "status": "unavailable",
     "no_spend": true
    },
    "external_action_allowed": false
   },
   "synthesis": {
    "status": "derived",
    "authority": "evaluation.commerce.opportunity_synthesis.build_product_opportunity_synthesis",
    "candidate_id": "desk-lamp-pro",
    "combined_opportunity_score": 0.831,
    "supplier_feasibility": 0.82,
    "consumer_attention": 0.8,
    "marketplace_opportunity": 0.86,
    "recommendation": "advance_to_launch_draft",
    "risk_profile": {
     "risk_level": "low",
     "supplier_risks": [],
     "marketplace_risks": [],
     "consumer_risks": [],
     "blockers": []
    }
   }
  },
  {
   "candidate_id": "monitor-riser",
   "recommendation": "needs_evidence",
   "readiness": "not_ready",
   "fatal_gates": [],
   "blockers": [],
   "evidence_gaps": [
    "affiliate_fee_rate",
    "brokerage_fee",
    "cac",
    "domestic_shipping",
    "international_shipping",
    "payment_fee_fixed",
    "platform_fee_fixed"
   ],
   "evidence_classes": [
    "derived",
    "fixture",
    "manual"
   ],
   "metrics": {
    "synthesis_score": 0.7875,
    "offering_kind": "product",
    "evidence_confidence": 0.6667,
    "economics_status": "derived",
    "economics_missing_inputs": [
     "affiliate_fee_rate",
     "brokerage_fee",
     "cac",
     "domestic_shipping",
     "international_shipping",
     "payment_fee_fixed",
     "platform_fee_fixed"
    ]
   },
   "scenarios": {
    "best": {
     "scenario": "upside",
     "currency": "MXN",
     "net_sales": {
      "amount": "945.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "72.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_domestic_shipping",
      "provenance": "assumed_domestic_shipping",
      "evidence_state": "unknown"
     },
     "international_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_international_shipping",
      "provenance": "assumed_international_shipping",
      "evidence_state": "unknown"
     },
     "duty": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "151.200000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_brokerage_fee",
      "provenance": "assumed_brokerage_fee",
      "evidence_state": "unknown"
     },
     "payment_fees": {
      "amount": "28.350000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "18.900000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "9.450000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0E-8",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_cac",
      "provenance": "assumed_cac",
      "evidence_state": "unknown"
     },
     "contribution_before_cac": {
      "amount": "359.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "359.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "359.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "170.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "585.90000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.3800",
     "contribution_margin_after_cac": "0.3800",
     "break_even_roas": "2.631578947368421052631578947",
     "target_roas": "5.555555555555555555555555556",
     "expected_return_cost": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": [
      "domestic_shipping",
      "international_shipping",
      "brokerage_fee",
      "payment_fee_fixed",
      "platform_fee_fixed",
      "cac",
      "affiliate_fee_rate"
     ]
    },
    "base": {
     "scenario": "base",
     "currency": "MXN",
     "net_sales": {
      "amount": "900.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "80",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_domestic_shipping",
      "provenance": "assumed_domestic_shipping",
      "evidence_state": "unknown"
     },
     "international_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_international_shipping",
      "provenance": "assumed_international_shipping",
      "evidence_state": "unknown"
     },
     "duty": {
      "amount": "0.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "144.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_brokerage_fee",
      "provenance": "assumed_brokerage_fee",
      "evidence_state": "unknown"
     },
     "payment_fees": {
      "amount": "27.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "9.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_cac",
      "provenance": "assumed_cac",
      "evidence_state": "unknown"
     },
     "contribution_before_cac": {
      "amount": "298.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "298.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "298.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "118.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "602.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.3311111111111111111111111111",
     "contribution_margin_after_cac": "0.3311111111111111111111111111",
     "break_even_roas": "3.020134228187919463087248322",
     "target_roas": "7.627118644067796610169491525",
     "expected_return_cost": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "18.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": [
      "domestic_shipping",
      "international_shipping",
      "brokerage_fee",
      "payment_fee_fixed",
      "platform_fee_fixed",
      "cac",
      "affiliate_fee_rate"
     ]
    },
    "worst": {
     "scenario": "downside",
     "currency": "MXN",
     "net_sales": {
      "amount": "810.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "product_cost": {
      "amount": "300",
      "currency": "MXN",
      "source": "manual",
      "provenance": "manual",
      "evidence_state": "observed"
     },
     "supplier_shipping": {
      "amount": "96.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "domestic_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_domestic_shipping",
      "provenance": "assumed_domestic_shipping",
      "evidence_state": "unknown"
     },
     "international_shipping": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_international_shipping",
      "provenance": "assumed_international_shipping",
      "evidence_state": "unknown"
     },
     "duty": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "tax": {
      "amount": "129.600000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "brokerage": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_brokerage_fee",
      "provenance": "assumed_brokerage_fee",
      "evidence_state": "unknown"
     },
     "payment_fees": {
      "amount": "24.300000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "platform_fees": {
      "amount": "16.200000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "marketplace_fees": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "affiliate_fees": {
      "amount": "0.0000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "return_reserve": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_reserve": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "support_reserve": {
      "amount": "8.100000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "chargeback_reserve": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "fx_reserve": {
      "amount": "0E-8",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "cac": {
      "amount": "0",
      "currency": "MXN",
      "source": "assumed_cac",
      "provenance": "assumed_cac",
      "evidence_state": "unknown"
     },
     "contribution_before_cac": {
      "amount": "173.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_after_cac": {
      "amount": "173.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "break_even_cac": {
      "amount": "173.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "target_cac": {
      "amount": "11.10000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "unknown"
     },
     "cash_required_per_order": {
      "amount": "636.90000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_lag_exposure": {
      "amount": "0.000000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "contribution_margin": "0.2137037037037037037037037037",
     "contribution_margin_after_cac": "0.2137037037037037037037037037",
     "break_even_roas": "4.679376083188908145580589255",
     "target_roas": "72.97297297297297297297297297",
     "expected_return_cost": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "refund_loss": {
      "amount": "56.700000",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "defect_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "warranty_cost": {
      "amount": "3.00",
      "currency": "MXN",
      "source": "derived",
      "provenance": "derived",
      "evidence_state": "observed"
     },
     "evidence_state": "assumed",
     "missing_inputs": [
      "domestic_shipping",
      "international_shipping",
      "brokerage_fee",
      "payment_fee_fixed",
      "platform_fee_fixed",
      "cac",
      "affiliate_fee_rate"
     ]
    }
   },
   "sensitivity_drivers": [
    "evidence freshness"
   ],
   "experiment": {
    "experiment_id": "experiment-monitor-riser",
    "question": "Does bounded freight evidence preserve a non-negative landed contribution?",
    "method": "offline_sanitized_evidence_review",
    "required_evidence": [
     "shipping quote",
     "lane",
     "delivery promise"
    ],
    "success_thresholds": {
     "required_evidence_count": 1,
     "decision_change": "all fatal gates clear"
    },
    "kill_thresholds": {
     "decision_change": "retain_block_or_reject"
    },
    "iterate_rule": "iterate only when new bounded evidence changes a named blocker; otherwise stop",
    "estimated_cost": {
     "currency": "unknown",
     "amount": "unknown",
     "status": "unavailable",
     "no_spend": true
    },
    "external_action_allowed": false
   },
   "synthesis": {
    "status": "derived",
    "authority": "evaluation.commerce.opportunity_synthesis.build_product_opportunity_synthesis",
    "candidate_id": "monitor-riser",
    "combined_opportunity_score": 0.7875,
    "supplier_feasibility": 0.8,
    "consumer_attention": 0.75,
    "marketplace_opportunity": 0.8,
    "recommendation": "advance_to_launch_draft",
    "risk_profile": {
     "risk_level": "low",
     "supplier_risks": [],
     "marketplace_risks": [],
     "consumer_risks": [],
     "blockers": []
    }
   }
  },
  {
   "candidate_id": "restricted-category",
   "recommendation": "blocked",
   "readiness": "blocked",
   "fatal_gates": [
    "restricted_or_legal_category",
    "supply_unproven"
   ],
   "blockers": [
    "economics_unavailable",
    "restricted_or_legal_category",
    "supply_unproven"
   ],
   "evidence_gaps": [
    "marketplace_supplier_consumer_reports_unavailable",
    "price",
    "product_cost",
    "reachable_buyer_evidence_unavailable",
    "shipping",
    "supplier_evidence_unavailable"
   ],
   "evidence_classes": [
    "fixture"
   ],
   "metrics": {
    "synthesis_score": null,
    "offering_kind": "hybrid",
    "evidence_confidence": 0.0,
    "economics_status": "unavailable",
    "economics_missing_inputs": [
     "price",
     "product_cost",
     "shipping"
    ]
   },
   "scenarios": {
    "best": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    },
    "base": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    },
    "worst": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    }
   },
   "sensitivity_drivers": [
    "supplier evidence",
    "landed cost",
    "reachable buyer",
    "compliance"
   ],
   "experiment": {
    "experiment_id": "experiment-restricted-category",
    "question": "Can a sanitized supplier record prove availability, cost, and delivery for this candidate?",
    "method": "offline_sanitized_evidence_review",
    "required_evidence": [
     "supplier identity",
     "cost",
     "availability",
     "delivery"
    ],
    "success_thresholds": {
     "required_evidence_count": 1,
     "decision_change": "all fatal gates clear"
    },
    "kill_thresholds": {
     "decision_change": "retain_block_or_reject"
    },
    "iterate_rule": "iterate only when new bounded evidence changes a named blocker; otherwise stop",
    "estimated_cost": {
     "currency": "unknown",
     "amount": "unknown",
     "status": "unavailable",
     "no_spend": true
    },
    "external_action_allowed": false
   },
   "synthesis": {
    "status": "unavailable",
    "authority": "evaluation.commerce.opportunity_synthesis.build_product_opportunity_synthesis"
   }
  },
  {
   "candidate_id": "supplier-claim-only",
   "recommendation": "blocked",
   "readiness": "blocked",
   "fatal_gates": [
    "supplier_claim_not_verification"
   ],
   "blockers": [
    "economics_unavailable",
    "supplier_claim_is_not_independent_verification",
    "supplier_claim_not_verification"
   ],
   "evidence_gaps": [
    "marketplace_supplier_consumer_reports_unavailable",
    "price",
    "product_cost",
    "reachable_buyer_evidence_unavailable",
    "shipping"
   ],
   "evidence_classes": [
    "observed"
   ],
   "metrics": {
    "synthesis_score": null,
    "offering_kind": "product",
    "evidence_confidence": 0.0,
    "economics_status": "unavailable",
    "economics_missing_inputs": [
     "price",
     "product_cost",
     "shipping"
    ]
   },
   "scenarios": {
    "best": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    },
    "base": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    },
    "worst": {
     "status": "unavailable",
     "missing_inputs": [
      "price",
      "product_cost",
      "shipping"
     ]
    }
   },
   "sensitivity_drivers": [
    "evidence freshness"
   ],
   "experiment": {
    "experiment_id": "experiment-supplier-claim-only",
    "question": "Can a sanitized supplier record prove availability, cost, and delivery for this candidate?",
    "method": "offline_sanitized_evidence_review",
    "required_evidence": [
     "supplier identity",
     "cost",
     "availability",
     "delivery"
    ],
    "success_thresholds": {
     "required_evidence_count": 1,
     "decision_change": "all fatal gates clear"
    },
    "kill_thresholds": {
     "decision_change": "retain_block_or_reject"
    },
    "iterate_rule": "iterate only when new bounded evidence changes a named blocker; otherwise stop",
    "estimated_cost": {
     "currency": "unknown",
     "amount": "unknown",
     "status": "unavailable",
     "no_spend": true
    },
    "external_action_allowed": false
   },
   "synthesis": {
    "status": "unavailable",
    "authority": "evaluation.commerce.opportunity_synthesis.build_product_opportunity_synthesis"
   }
  }
 ],
 "ranked_candidate_ids": [
  "desk-lamp-pro"
 ],
 "blockers": [
  "economics_unavailable",
  "restricted_or_legal_category",
  "supplier_claim_is_not_independent_verification",
  "supplier_claim_not_verification",
  "supply_unproven"
 ],
 "next_best_action": "run the cheapest bounded evidence experiment named for the leading candidate",
 "safety": {
  "read_only": true,
  "network_calls": false,
  "provider_calls": false,
  "credentials_present": false,
  "orders_created": false,
  "payments_created": false,
  "ads_launched": false,
  "publishing": false,
  "database_writes": false,
  "launch_authorized": false
 },
 "fingerprint": "b4aef12cacc1a0e8d333a4ad057222b66443097e725ebed7ad4d0440720e4509"
};
